spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:https://localhost:8888
  cloud:
    compatibility-verifier:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_CERTS_URL:http://localhost:8090/realms/wefit/protocol/openid-connect/certs}

server:
  port: 8443
  ssl:
    key-store: file:../certs/keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: wefit

user-service:
  base-url: ${USER_SERVICE_URL:http://localhost:8081}

management:
  endpoints:
    web:
      exposure:
        include: "*"