server:
  port: 8087
  ssl:
    key-store: ${WEFIT_KEYSTORE:file:../certs/keystore.p12}
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: wefit

spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID:minioadmin}
        secret-key: ${AWS_SECRET_ACCESS_KEY:minioadmin}
      region:
        static: ${AWS_REGION:us-east-1}
      s3:
        endpoint: ${AWS_S3_ENDPOINT:http://localhost:9000}
        path-style-access: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true

wefit:
  media:
    bucket-name: ${S3_BUCKET_NAME:wefit-media}
