spring:
  application:
    name: user-service
  datasource:
    url: ${DB_URL_USER_SERVICE:jdbc:postgresql://localhost:5432/wefit}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate.format_sql: true
    generate-ddl: false
  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8081
  ssl:
    key-store: file:../certs/keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: wefit

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:https://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
    secure-port-enabled: true
    non-secure-port-enabled: false
